#Chatbot Sederhana N0 4
print ("Chat Bot Sederhana")
print("")
saya = input("\033[37m Silver Rayleigh : ")
print ("\033[36m Gol D Roger : Masi dong,kamu kan salah satu crew bajak laut ku dulu")
saya = input("\033[37m Silver Rayleigh : ")
print ("\033[36m Gol D Roger : Biasalah, santai santai aja nunggu si luffy di Laugh Tale")
saya = input("\033[37m Silver Rayleigh : ")
print ("\033[36m Gol D Roger : Ada Shanks tadi cuman udah pergi lagi dia singgah bentar tadi")
saya = input("\033[37m Silver Rayleigh : ")
print ("\033[36m Gol D Roger : Oke brodi aman")